### ISSUE TITLE
Conflict with Essential Addons

### ISSUE THREAD

**Issue by becauseimgray** [altrisi/DropFullCarts#2] opened 2022-05-19 07:54 UTC
Hi, I'm running a modded fabric server on 1.18.2 and I dropped your mod in recently, but now I'm finding that minecarts are dropping as the base item, losing the chest, furnace, etc. item in the process instead of receiving a "chest minecart" item. If I put items into the chest minecart and break it, I get the items + a base minecart but no chest or chest minecart item. I'm getting 0 errors in the console related to minecarts, so I'm not sure what could be causing the issue. Please let me know if there is anything I can provide that would help resolve this. 

This is my console output after server restart:
https://mcpaste.io/4a631d18ec72cc74

**Comment by altrisi** [comment] 2022-05-19 13:49
Hmm, there must be a conflict with some of your mods replacing the logic that DropFullCarts adds. The log doesn't seem to give any info as to what it is.

After looking for a possible cause though, I think this could be caused by "EssentialAddons", given they are using a bad technique with mixins where they silently cancel any modified logic and then just replicate vanilla behaviour, and given they have injections where DropFullCarts needs to go, it may be preventing it from working.

I made an issue about the technique they use on their repo: Super-Santa/EssentialAddons#39.

**Comment by altrisi** [comment] 2022-05-19 13:51
May not be it though, I haven't tested it. If it's not you should try binary search and if you can find what mod causes it then I can try to see if there's something I can do.

**Comment by becauseimgray** [comment] 2022-05-19 21:03
I went ahead and disabled Essential Addons on the server, and the issue immediately went away! Looks like you were spot on about that being the problem. Unfortunately, we were using Essential Addons for quite a few things on the server, so I won't be able to keep it disabled but I'll keep my eyes peeled for a good alternative to it so I can keep using your mod, thank you!

**Comment by altrisi** [comment] 2022-05-25 19:57
I submitted a fix for this to EssentialAddons, once it's merged and released this should be fixed.

**Comment by altrisi** [comment] 2022-06-12 09:48
This should be fixed with the last update of EssentialAddons.

**Closed as completed by altrisi** 2022-06-12 09:48 UTC
